Continuing the installation script: finished --install-ruby and added --checkout.

diff --git a/script/mconf-web-conf b/script/mconf-web-conf
--- a/script/mconf-web-conf
+++ b/script/mconf-web-conf
@@ -17,8 +17,16 @@
 #
 
 MCONF_WEB_VERSION="0.2"
+
 IP=$(ifconfig | grep -v '127.0.0.1' | grep -E "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | head -1 | cut -d: -f2 | awk '{print $1}')
-RVM_VERSION="1.5.2"
+
+RVM_VERSION=1.5.2
+RVM_RUBY_VERSION=1.9.2
+RVM_GEMSET=mconf
+
+CHECKOUT_REPO=git://github.com/mconf/mconf-web.git
+CHECKOUT_SRC_DIR=~/dev/source/mconf-web
+CHECKOUT_BRANCH=master
 
 
 #
@@ -32,7 +40,10 @@ usage() {
     echo "   mconf-web-conf [options]"
     echo
     echo "Setup and configuration:"
-    echo "   --install-ruby                    Install ruby (using RVM)"
+    echo "   --install-ruby                   Install ruby (using RVM)"
+    echo "Development:"
+    echo "   --checkout <repo>                Checkout from github or <repo> (default: $CHECKOUT_REPO)"
+
 #    echo "Administration:"
 #    echo "   --restart                        Restart the web server"
 #    echo "   --stop                           Stop the web server"
@@ -96,14 +107,42 @@ check_root() {
 # }
 
 # Install a package in the system
-# $1 package and binary name
+# $1 is the package and binary name
 install_dependency() {
     which $1
     if [ $? != 0 ]; then
         echo "** Installing dependency: $1"
         sudo apt-get install $1 -y --force-yes
+    else
+        echo "** Dependency '$1' already installed"
     fi
 }
+
+# Install a list of packages in the system
+# $1 is the list of packages
+install_dependencies() {
+    echo "** Installing dependencies: $1"
+    sudo apt-get install $1 -y --force-yes
+}
+
+# Prints a nice "banner" in the console with the text in
+# $1 in the center
+print_banner() {
+    echo "-----------------------------"
+    echo "$1"
+    echo "-----------------------------"
+}
+
+# Prints a nice error "banner" in the console with the text in
+# $1 in the center
+print_error_banner() {
+    echo "*****************************"
+    echo "ERROR: $1"
+    echo "*****************************"
+}
+
+
+
 
 #
 # Parse the parameters
@@ -112,10 +151,24 @@ install_dependency() {
 while [ $# -gt 0 ]; do
 
     if [ "$1" = "--install-ruby" -o "$1" = "-install-ruby" ]; then
+        echo "* Request to install RVM/Ruby"
         RUBY=1
         shift
         continue
     fi
+
+    if [ "$1" = "--checkout" -o "$1" = "-checkout" ]; then
+        echo "* Request to checkout Mconf-Web"
+        CHECKOUT=1
+        shift
+        if [ $# -ge 1 ]; then
+            CHECKOUT_REPO="${1}"
+            shift
+        fi
+        echo "** Checkout from: $CHECKOUT_REPO"
+        continue
+    fi
+
 
 #    if [ "$1" = "-stop" -o "$1" = "--stop" ]; then
 #        stop_bigbluebutton
@@ -143,29 +196,37 @@ while [ $# -gt 0 ]; do
 done
 
 
+#
 # Version
 # TODO
+
 if [ $VERSION ]; then
     echo
 #    dpkg -l | grep bbb
     exit 0
 fi
 
+
+
+#
+# Install Ruby
+#
+
 # Check if rvm is installed
 # Returns true or false in $RVM_INSTALLED
 rvm_check() {
     RVMTYPE=`type rvm | head -1`
     if [ "$RVM_TYPE" != "rvm is a function" ]; then
-	RVM_INSTALLED=true
+        RVM_INSTALLED=true
     else
-	RVM_INSTALLED=false
+        RVM_INSTALLED=false
     fi
 }
 
-# Installs RVM
+# Installs the base of RVM
+# TODO: install RVM as root?
 rvm_install() {
-    install_dependency curl
-    install_dependency git
+    install_dependencies "curl git"
     curl -s https://rvm.beginrescueend.com/install/rvm -o rvm-installer ; chmod +x rvm-installer ; ./rvm-installer --version $RVM_VERSION
     touch ~/.bash_profile
     if ! cat ~/.bash_profile | grep -q ".rvm/scripts/rvm"; then
@@ -175,6 +236,24 @@ rvm_install() {
     # bash < <(curl -s https://rvm.beginrescueend.com/install/rvm) # to install the latest version only
 }
 
+# Install system packages suggested by "rvm notes"
+# Uses the section "For Ruby (MRI & ree)  you should install the following OS dependencies"
+rvm_notes_install_packages() {
+    RVM_PACKAGES=`rvm notes | grep "^\s*ruby:.*aptitude install" | head -1 | sed 's/.*aptitude install //g'`
+    install_dependencies "$RVM_PACKAGES"
+}
+
+# Installs ruby using rvm and creates the default gemset
+rvm_ruby_and_gemset() {
+    if ! rvm list | grep -q $RVM_RUBY_VERSION; then
+        rvm install $RVM_RUBY_VERSION
+    fi
+    rvm use $RVM_RUBY_VERSION
+    rvm gemset clear
+    rvm gemset create $RVM_GEMSET
+    rvm use $RVM_RUBY_VERSION@$RVM_GEMSET # TODO: --default
+}
+
 
 if [ $RUBY ]; then
     check_root
@@ -182,13 +261,74 @@ if [ $RUBY ]; then
     # installs RVM if not present (https://rvm.beginrescueend.com/rvm/install/)
     rvm_check
     if [ $RVM_INSTALLED ]; then
-        echo "* RVM already installed at $(which rvm)"
+        echo "** RVM already installed at $(which rvm)"
     else
-        echo "* Installing RVM..."
-	rvm_install
+        echo "** Installing RVM..."
+        rvm_install
     fi
 
-    # TODO: install packages from "rvm notes"
-    # TODO: install ruby 1.9.2 and gemset
+    rvm_check
+    if [ $RVM_INSTALLED ]; then
+        rvm_notes_install_packages
+        rvm_ruby_and_gemset
+        print_banner "RVM/Ruby installed successfully."
+    else
+        print_error_banner "Something went wrong installing ruby. You'll have to do it manually."
+    fi
+fi
 
+
+
+#
+# Setup the development environemnt.
+#
+
+# Check if the destination dir exists and if it has a copy of mconf-web already there
+# Sets $CHECKOUT_UPDATE if the above is true
+# Exists if the dir exists and has something else than mconf-web
+checkout_check_update() {
+    if [ -d $CHECKOUT_SRC_DIR ]; then
+        # checks a signature file to see if it's mconf-web at the destination dir or not
+        cd  $CHECKOUT_SRC_DIR
+        CHECKOUT_UPDATE=""
+        if [ -f ./config/version.rb ]; then
+            if cat ./config/version.rb | grep -q "module Vcc"; then
+                CHECKOUT_UPDATE=true
+            fi
+        fi
+        if [ ! $CHECKOUT_UPDATE ]; then
+            print_error_banner "$CHECKOUT_SRC_DIR already exists. Please delete it to be able to checkout Mconf-Web."
+            exit 1
+        fi
+    fi
+}
+
+if [ $CHECKOUT ]; then
+    check_root
+
+    install_dependency "git"
+    checkout_check_update
+
+    echo "** Creating the src directory: $CHECKOUT_SRC_DIR"
+    mkdir -p $CHECKOUT_SRC_DIR
+
+    if [ $CHECKOUT_UPDATE ]; then
+        cd $CHECKOUT_SRC_DIR
+
+        echo "** Checking out branch $CHECKOUT_BRANCH"
+        git checkout $CHECKOUT_BRANCH
+
+        echo "** Pulling $CHECKOUT_BRANCH from origin."
+        git pull origin $CHECKOUT_BRANCH
+    else
+        echo "** Cloning Mconf-Web."
+        cd  $CHECKOUT_SRC_DIR/../
+        git clone $CHECKOUT_REPO $CHECKOUT_SRC_DIR
+
+        cd $CHECKOUT_SRC_DIR
+        echo "** Checking out branch $CHECKOUT_BRANCH"
+        git checkout $CHECKOUT_BRANCH
+    fi
+
+    print_banner "Checked out Mconf-Web"
 fi
